### PR TITLE
Use task pool instead of handwritten implementation

### PR DESCRIPTION
**Pull request by kayceesrk**

### CODE REVIEW

**Comment by athas** [comment]
This code does not compile for me:

```
+ ocamlfind ocamlc -c -g -bin-annot -package domainslib -o ray.cmo ray.ml
File "ray.ml", line 1, characters 14-29:
Error: Unbound module Domainslib.Task
Command exited with code 2.
```

**Comment by kayceesrk** [comment]
Can you check `domainslib` version? `opam list domainslib`. It should be 0.2.0. To upgrade, please do:

```
$ opam update
$ opam install domainslib.0.2.0
```

**Comment by athas** [comment]
It works!  And it's a bit faster, too.

**Comment by kayceesrk** [comment]
Great. I'm happy that all the boilerplate is now gone.

**Comment by rand00** [comment]
Cool that the task interface fits the problems here! I'm wondering if it would make sense to make the pool of size `num_domains`? The main domain is just waiting for the others to finish work?

**Comment by kayceesrk** [comment]
> Cool that the task interface fits the problems here! I'm wondering if it would make sense to make the pool of size num_domains? The main domain is just waiting for the others to finish work?

The main domain does participate in working on tasks. For example, you can create a pool with `num_domains` as 0; 0 indicates the number of *additional* domains. I'll clarify this in the API docs.

**Comment by rand00** [comment]
Ah cool

**Comment by rand00** [comment]
Just had a look at `Domainslib.Task.setup_pool` - there is only spawned a worker per `num_domains` - so the only work the main domain does is the work up until one calls `Task.await pool <foo>`, if `<foo>` contains a recursive call to the same function, correct?

**Comment by rand00** [comment]
Ah sorry - it's `await` that also is a worker

**Comment by kayceesrk** [comment]
Yeah. The idea is to set up the pool (which essentially sets up a shared channel as a work-stealing queue). The worker domains first wait on the channel for tasks and execute them when one is available. And as you've observed, `await` waits for task completion, but also continues to process tasks.

**Pull request merged**
