### PR TITLE
Multicore OCaml raytracer, ported from F# version

### PR DESCRIPTION
**Pull request by rand00**

### CODE REVIEW

**Comment by athas** [comment]
Looks fun!  I'll see if I can get multicore OCaml working.  Hopefully someone has a Nix derivation somewhere...

**Comment by rand00** [comment]
(: Yes that would be practical, but I think the multicore OCaml switch is too new to be in Nix. It should be simple enough to follow the guides linked in the readme

**Comment by athas** [comment]
I managed to run and measure the performance (using the C FFI to access `gettimeofday()`).  Performance is awful!  I really hope this is going to improve a lot in the future.

**Comment by rand00** [comment]
(: It should improve a lot - it is not nearly finished. Seems to me that they are gaining pace though. Should be interesting to follow their progress by running the raytracer in the future. They have a repo with other benchmarks here: https://github.com/ocaml-bench/sandmark

**Pull request merged**
